### ISSUE TITLE
[META] Improve error messaging and exception handling

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#281]
This is the meta issue for tracking all of the effort required for error messaging and exception handling.

- [x] https://github.com/opensearch-project/opensearch-spark/issues/201
- [x] https://github.com/opensearch-project/opensearch-spark/issues/252
- [x] https://github.com/opensearch-project/opensearch-spark/issues/264
- [ ] https://github.com/opensearch-project/opensearch-spark/issues/275
- [ ] https://github.com/opensearch-project/opensearch-spark/issues/259
- [x] https://github.com/opensearch-project/opensearch-spark/issues/280

**Comment by dai-chen** [comment]
Related: https://github.com/opensearch-project/opensearch-spark/issues/101

**Comment by dai-chen** [comment]
Closing. Fixed all error message problem in the issue list above.
