### ISSUE TITLE
[FEATURE] Support Spark 3.4.1

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#331]
**Is your feature request related to a problem?**
* https://github.com/opensearch-project/opensearch-spark/issues/89#issuecomment-1965460982

**What solution would you like?**
* Support Spark 3.4.1

**Tasks**
- [x] Cut feature branch for Spark 3.4.1.
- [ ] Made code change, Fix IT
  - [x] https://github.com/opensearch-project/opensearch-spark/pull/341
  - [x] https://github.com/opensearch-project/opensearch-spark/issues/319
  - [ ] https://github.com/opensearch-project/opensearch-spark/pull/349
  - [x] https://github.com/opensearch-project/opensearch-spark/pull/342
  - [x] https://github.com/opensearch-project/opensearch-spark/pull/345
- [ ] Bechmark Flint Performance with Spark 3.4.1.
- [ ] Release with Flint 0.5.

**Comment by penghuo** [comment]
Known Issue of Spark upgrade
* https://github.com/opensearch-project/opensearch-spark/issues/319

**Comment by penghuo** [comment]
## Issues with Spark 3.4.1
* https://issues.apache.org/jira/browse/SPARK-39139, Spark 3.4 unifiy Predicates.toString method, but it only support native operator, `BLOOM_FILTER_MIGHT_CONTAIN` is customized Predicates, when call toString, it throw [IllegalArgumentException](https://github.com/apache/spark/blob/branch-3.4/sql/catalyst/src/main/java/org/apache/spark/sql/connector/util/V2ExpressionSQLBuilder.java#L377). It is not a issue on Spark 3.3, the reasons is Exception is catched by https://github.com/apache/spark/blob/branch-3.3/sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/GeneralScalarExpression.java#L184

**Comment by penghuo** [comment]
## Issue with Iceberg
* DROP TABLE does works, env: Spark 3.4.1  + Iceberg 1.5.2
```
./bin/spark-sql --packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.5.2\
    --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hadoop \
    --conf spark.sql.catalog.spark_catalog.warehouse=$PWD/warehouse

spark-sql (default)> CREATE TABLE spark_catalog.default.t1 (age INT) USING iceberg;
Time taken: 1.288 seconds
spark-sql (default)> SELECT * FROM spark_catalog.default.t1;
Time taken: 0.704 seconds
spark-sql (default)> DROP TABLE spark_catalog.default.t1;
[TABLE_OR_VIEW_NOT_FOUND] The table or view `spark_catalog`.`default`.`t1` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.

```

**Comment by asuresh8** [comment]
If you run `SHOW TABLE` after creating the table, what shows up? I'm curious what the issue is here if there is some permission issue or the table is getting created in an unexpected catalog?

**Comment by asuresh8** [comment]
I tried to reproduce and wasn't able to. The table dropped just fine. Maybe you don't have permissions in directory you created the table in?

**Comment by dai-chen** [comment]
Will track in new issue https://github.com/opensearch-project/opensearch-spark/issues/352.
